# Generated by Django 5.2 on 2025-04-24 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subdomain', models.CharField(help_text="Subdomain prefix for the MFI (e.g., 'acme' for 'acme.letsema.com')", max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Subdomain can only contain lowercase letters, numbers, and hyphens. It cannot start or end with a hyphen.', regex='^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Microfinance Institution',
                'verbose_name_plural': 'Microfinance Institutions',
            },
        ),
    ]
