# Generated by Django 5.2 on 2025-04-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrofinanceInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
